export const actionTypes = {
  SET_SONGSHEET_DETAIL: 'SONGSHEET/SET_SONGSHEET_DETAIL',
  SET_SONG_LIST: 'SONGSHEET/SET_SONG_LIST',
  SET_HOT_COMMENT: 'SONGSHEET/SET_HOT_COMMENT',
  SET_NEW_COMMENT: 'SONGSHEET/SET_NEW_COMMENT',
  SET_RELATED_SONGSHEET: 'SONGSHEET/SET_RELATED_SONGSHEET'
}
