export const actionTypes = {
  SET_SONG_LIST: 'PLAYER/SET_SONG_LIST',
  SET_CURRENT_INDEX: 'PLAYER/SET_CURRENT_INDEX',
  SET_CURRENT_LYRIC: 'PLAYER/SET_CURRENT_LYRIC',
  SET_CURRENT_LYRIC_INDEX: 'PLAYER/SET_CURRENT_LYRIC_INDEX',
  SET_PLAYER_STATUS: 'PLAYER/SET_PLAYER_STATUS'
}
