export const actionTypes = {
  SET_SONG_LIST: 'player/SET_SONG_LIST',
  SET_CURRENT_SONG: 'player/SET_CURRENT_SONG',
  SET_CURRENT_SONG_INDEX: 'player/SET_CURRENT_SONG_INDEX',
  SET_CURRENT_LYRIC: 'player/SET_CURRENT_LYRIC',
  SET_CURRENT_LYRIC_INDEX: 'player/SET_CURRENT_LYRIC_INDEX',
  SET_IS_INITED: 'player/SET_IS_INITED'
}
