export const actionTypes = {
  SET_SONG_DETAIL: 'SONG/SET_SONG_DETAIL',
  SET_SONG_LYRIC: 'SONG/SET_SONG_LYRIC',
  SET_HOT_COMMENT: 'SONG/SET_HOT_COMMENT',
  SET_NEW_COMMENT: 'SONG/SET_NEW_COMMENT',
  SET_SIMI_SONGSHEET_LIST: 'SONG/SET_SIMI_SONGSHEET_LIST',
  SET_SIMI_SONG_LIST: 'SONG/SET_SIMI_SONG_LIST'
}
