export const actionTypes = {
  SET_TOP_BANNER_LIST: 'DISCOVER_RECOMD/SET_TOP_BANNER_LIST',
  SET_HOT_RECOMD_LIST: 'DISCOVER_RECOMD/SET_HOT_RECOMD_LIST',
  SET_NEW_ALBUM_LIST: 'DISCOVER_RECOMD/SET_NEW_ALBUM_LIST',
  SET_RANK_MULTI_LIST: 'DISCOVER_RECOMD/SET_RANK_MULTI_LIST',
  SET_HOT_ARTISTS_LIST: 'DISCOVER_RECOMD/SET_HOT_ARTISTS_LIST'
}
