export const SET_SONG_LIST = 'player/SET_SONG_LIST'
export const SET_CURRENT_SONG = 'player/SET_CURRENT_SONG'
export const SET_CURRENT_INDEX = 'player/SET_CURRENT_INDEX'
export const SET_PLAY_MODE = 'player/SET_PLAY_MODE'
export const SET_IS_INITED = 'player/SET_IS_INITED'
