export const actionTypes = {
  SET_TOP_CATEGORIES: 'DISCOVER_TOPLIST/SET_TOP_CATEGORIES',
  SET_CURRENT_TOP: 'DISCOVER_TOPLIST/SET_CURRENT_TOP',
  SET_CURRENT_SONG_LIST: 'DISCOVER_TOPLIST/SET_CURRENT_SONG_LIST',
}
