export const actionTypes = {
  SET_CHART_LIST: 'DISCOVER_TOPLIST/SET_CHART_LIST',
  SET_CURRENT_CHART: 'DISCOVER_TOPLIST/SET_CURRENT_CHART',
  SET_CURRENT_CHART_DETAIL: 'DISCOVER_TOPLIST/SET_CURRENT_CHART_DETAIL',
  SET_CURRENT_CHART_SONG_LIST: 'DISCOVER_TOPLIST/SET_CURRENT_CHART_SONG_LIST',
  SET_HOT_COMMENT: 'DISCOVER_TOPLIST/SET_HOT_COMMENT',
  SET_NEW_COMMENT: 'DISCOVER_TOPLIST/SET_NEW_COMMENT'
}
