export const actionTypes = {
  SET_CAT_LIST: 'DISCOVER_SONGSHEET/SET_CAT_LIST',
  SET_CURRENT_CAT: 'DISCOVER_SONGSHEET/SET_CURRENT_CAT',
  SET_SONGSHEET_DATA: 'DISCOVER_SONGSHEET/SET_SONGSHEET_DATA'
}
