export const SET_CAROUSEL_IMAGES = 'recomd/SET_CAROUSEL_IMAGES'
export const SET_HOT_RECOMD_LIST = 'recomd/SET_HOT_RECOMD_LIST'
export const SET_NEW_ALBUM_LIST = 'recomd/SET_NEW_ALBUM_LIST'
export const SET_RANK_MULTI_UP = 'recomd/SET_RANK_MULTI_UP'
export const SET_RANK_MULTI_NEW = 'recomd/SET_RANK_MULTI_NEW'
export const SET_RANK_MULTI_ORG = 'recomd/SET_RANK_MULTI_ORG'
export const SET_SETTLE_SINGER_LIST = 'recomd/SET_SETTLE_SINGER_LIST'
