export const SET_BANNER = 'recomd/SET_BANNER'
export const SET_PERSONALIZED = 'recomd/SET_PERSONALIZED'
export const SET_TOP_ALBUM = 'recomd/SET_TOP_ALBUM'
export const SET_TOP_LIST_UP = 'recomd/SET_TOP_LIST_UP'
export const SET_TOP_LIST_NEW = 'recomd/SET_TOP_LIST_NEW'
export const SET_TOP_LIST_ORG = 'recomd/SET_TOP_LIST_ORG'
export const SET_ARTIST_LIST = 'recomd/SET_ARTIST_LIST'
