export const actionTypes = {
  SET_CAROUSEL_IMAGES: 'recomd/SET_CAROUSEL_IMAGES',
  SET_HOT_RECOMD_LIST: 'recomd/SET_HOT_RECOMD_LIST',
  SET_NEW_ALBUM_LIST: 'recomd/SET_NEW_ALBUM_LIST',
  SET_RANK_MULTI_LIST: 'recomd/SET_RANK_MULTI_LIST',
  SET_SETTLE_SINGER_LIST: 'recomd/SET_SETTLE_SINGER_LIST'
}
